# Generated by Django 3.1.5 on 2021-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default='2021-01-27 21:19:37', verbose_name='comment date'),
        ),
        migrations.AddField(
            model_name='like',
            name='like_date',
            field=models.DateField(default='2021-01-27 21:19:37', verbose_name='like date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default='2021-01-27 21:19:37', verbose_name='post date'),
        ),
    ]
