# Generated by Django 3.1.3 on 2021-03-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210224_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='username',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posting.category', verbose_name='پدر'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='image',
            field=models.FileField(blank=True, upload_to='media/user/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='media/post/', verbose_name='عکس'),
        ),
    ]
