# Generated by Django 3.1.5 on 2021-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210127_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default='2021-01-27 21:22:26', verbose_name='comment date'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_date',
            field=models.DateTimeField(default='2021-01-27 21:22:26', verbose_name='like date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default='2021-01-27 21:22:26', verbose_name='post date'),
        ),
    ]
