# Generated by Django 3.1.3 on 2021-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210210_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/user/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='phone_number',
            field=models.IntegerField(blank=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='عکس'),
        ),
    ]
