# Generated by Django 3.1.3 on 2021-03-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20210303_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/user/', verbose_name='عکس'),
        ),
    ]
