# Generated by Django 3.1.3 on 2021-02-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20210215_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.BooleanField(default=False, editable=False, verbose_name='لایک'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posting.comment', verbose_name='کامنت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.BooleanField(default=False, editable=False, verbose_name='لایک'),
        ),
    ]
