# Generated by Django 3.1.5 on 2021-01-27 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20210127_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 21, 38, 44, 604525), verbose_name='comment date'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 21, 38, 44, 604525), verbose_name='like date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 21, 38, 44, 604525), verbose_name='post date'),
        ),
    ]
