# Generated by Django 3.1.3 on 2021-03-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20210303_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='image',
            field=models.ImageField(blank=True, upload_to='user/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post/', verbose_name='عکس'),
        ),
    ]
