# Generated by Django 3.1.5 on 2021-01-27 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20210127_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 21, 40, 25, 536387), verbose_name='comment date'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 21, 40, 25, 536387), verbose_name='like date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 21, 40, 25, 537386), verbose_name='post date'),
        ),
    ]
