# Generated by Django 3.1.3 on 2021-02-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_bloguser_نام کاربری'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='نام کاربری',
            new_name='username',
        ),
    ]
