# Generated by Django 3.1.5 on 2021-01-27 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20210127_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 18, 17, 28, 377062, tzinfo=utc), verbose_name='comment date'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 18, 17, 28, 377062, tzinfo=utc), verbose_name='like date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 18, 17, 28, 377062, tzinfo=utc), verbose_name='post date'),
        ),
    ]
