# Generated by Django 3.1.5 on 2021-01-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_auto_20210127_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
